services:
  weaviate:
    image: semitechnologies/weaviate:1.24.5
    # ports:
    expose:
    - 8080
    - 50051
    volumes:
    - weaviate_data:/var/lib/weaviate
    restart: on-failure:0
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      DEFAULT_VECTORIZER_MODULE: 'none'
      CLUSTER_HOSTNAME: 'node1'
  ingest:
    image: myexpertchat:latest
    ports:
    - 8000:8005
    volumes:
    - llm_data:/data/
    environment:
      HF_HOME: '/data/huggingface'
      MYEXPERTCHAT_WEAVIATE_URL: 'http://weaviate:8080'
    command: gunicorn /app/ingest:app



    # volumes:
    # -model_cache:/home/user/.cache/huggingface
volumes:
  weaviate_data:
  llm_data: